"""empty message

Revision ID: 218111050a2e
Revises: 
Create Date: 2018-07-16 14:40:06.241027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218111050a2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=False),
    sa.Column('path_to_image', sa.String(), nullable=True),
    sa.Column('url_for_image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_header'), 'post', ['header'], unique=False)
    op.create_index(op.f('ix_post_pub_date'), 'post', ['pub_date'], unique=False)
    op.create_table('title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('path_to_image', sa.String(), nullable=True),
    sa.Column('url_for_image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('moder', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('number', sa.Float(), nullable=True),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('path_to_image', sa.String(), nullable=True),
    sa.Column('url_for_image', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['title.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_number'), 'chapter', ['number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chapter_number'), table_name='chapter')
    op.drop_table('chapter')
    op.drop_table('user')
    op.drop_table('title')
    op.drop_index(op.f('ix_post_pub_date'), table_name='post')
    op.drop_index(op.f('ix_post_header'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
