"""empty message

Revision ID: 3d66c7c877d1
Revises: 218111050a2e
Create Date: 2018-07-16 15:03:42.962829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d66c7c877d1'
down_revision = '218111050a2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('description', sa.String(), nullable=True))
    op.add_column('title', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('title', 'description')
    op.drop_column('chapter', 'description')
    # ### end Alembic commands ###
